application: tu-cedula
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: tucedula.app

libraries:
- name: jinja2
  version: latest 

builtins:
- remote_api: on
